services:
  pea-energy-app:
    build: .
    ports:
      - "3000:3000"
    env_file:             
      # ระบุ Path เต็มฝั่งเครื่อง Host
      - /home/hogzilla/.env
    volumes:
      - /home/hogzilla/data:/app/data
    restart: always