services:
  pea-energy-app:
    build: .
    ports:
      - "3030:3030"
    environment:
      - PORT=3030
      - NUXT_PORT=3030
    env_file:             
      - /home/hogzilla/.env.real
    volumes:
      - /home/hogzilla/data:/app/data
    restart: always